workflows:
  default:
    name: VForge
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk --release --target-platform android-arm
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk